server:
  port: 8083
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://url:3306/oicq?useUnicode=true&characterEncoding=UTF-8
    username: 用户名
    password: 密码
#  mail:
#    host: smtp.qq.com
#    username:
#    password:
#    protocol: smtp
#    default-encoding: UTF-8
#    test-connection: true
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
mybatis:
  type-aliases-package: com.demo1.Entity
  mapper-locations: classpath:/mybatis/*.xml